export const CLIENT_ACTION_TYPES = {
    SET_CURRENT_CLIENT : 'SET_CURRENT_CLIENT',
    SET_CLIENT_COBRO : 'SET_CLIENT_COBRO',
    CANCEL_CLIENT_COBRO : 'CANCEL_CLIENT_COBRO',
    ADD_CLIENT_DEBT : 'ADD_CLIENT_DEBT',
    REMOVE_DEBTS : 'REMOVE_DEBTS',
    REMOVE_DEBT : 'REMOVE_DEBT',
}
