export const CAJA_ACTION_TYPES = {
    SET_COBRO_CAJA : 'SET_COBRO_CAJA',
    SET_CATEGORIA_CONCEPTO : 'SET_CATEGORIA_CONCEPTO',
    SET_CONCEPTO : 'SET_CONCEPTO',
    SET_MOVIMIENTO : 'SET_MOVIMIENTO'

}
